## Numpy


In [2]:
import numpy as np

In [2]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [4]:
b = np.array(my_matrix)
b 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
## Array summary

print(b.ndim)

2


In [6]:
print(b.size)

12


In [7]:
print(b.dtype)

int64


In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
print(b.shape)

(3, 4)


In [10]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
arr1.shape

(2, 2, 3)

In [12]:
arr1.dtype

dtype('int64')

In [13]:
arr1.ndim

3

In [14]:
arr2 = np.array(["this","is"])
arr2

array(['this', 'is'], dtype='<U4')

In [38]:
print(np.mean([1,2,3,4,5]))
print(np.median([1,2,3,4,5]))
# print(np.mode([1,2,3,4,4,5])) 


3.0
3.0


In [ ]:
np.arange(15) # end ; default start at 0

In [ ]:
np.arange(2,15) ## Start , end and step

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.arange(0,10,2) # start end and step

array([0, 2, 4, 6, 8])

In [37]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### Zeros and ones

In [ ]:
np.zeros(3) # Generates array in 1 d with all elements 0

array([0., 0., 0.])

In [43]:
n = np.zeros(2)
n

array([0., 0.])

In [44]:
print(type(n))

<class 'numpy.ndarray'>


In [40]:
np.zeros((5,5)) ## Generates array in 2 dimensions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3) ## Generate array of 1 dimension where all element are 1

array([1., 1., 1.])

In [ ]:
np.ones((4,5,6)) # Generates array of 3 dimension where all elements are 1 

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Broadcasting in an array

In [47]:
big_one = np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
big_one.dtype

dtype('float64')

In [49]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### The ability to access each and every elements of an array is known as broadcasting

In [50]:
bigger_one = big_one * 6 - 2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [51]:
bigger = np.array(big_one*3 - 0.4 , dtype = "float")
print(bigger)

[[2.6 2.6 2.6 2.6]
 [2.6 2.6 2.6 2.6]
 [2.6 2.6 2.6 2.6]]


In [52]:
bigger.dtype

dtype('float64')

In [53]:
bigger = np.array(big_one*3 - 0.4 , dtype = "int")
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [54]:
bigger.dtype

dtype('int64')

In [55]:
bigger.shape

(3, 4)

In [56]:
print(type(bigger))

<class 'numpy.ndarray'>


In [57]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [60]:
arr + arr

array([0, 2, 4, 6])

In [61]:
arr * arr

array([0, 1, 4, 9])

In [66]:
array = ([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])
array[:5]

[0, 1, 2, 3, 4]

## Random number 

In [64]:
np.random.rand()

0.17574467841568764

In [ ]:
np.random.rand(10) #rand gives valuese between 0 and 1

array([0.45903647, 0.2388608 , 0.24837892, 0.17340638, 0.25759062,
       0.21920977, 0.87749391, 0.0703204 , 0.14341212, 0.44752158])

In [67]:
np.random.rand(5,2)

array([[0.23961914, 0.55079166],
       [0.69168201, 0.60730548],
       [0.21538767, 0.34496264],
       [0.77465408, 0.70918073],
       [0.32151668, 0.32290932]])

In [3]:
## Creating sample array 
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
len(arr)

21

In [5]:
arr[-1]

np.int64(20)

In [60]:
arr= np.arange(10,100,5)
# arr[:10]
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [8]:
len(arr)

18

In [9]:
arr[-1]

np.int64(95)

In [15]:
arr[0]

np.int64(10)

In [61]:
print(arr[0])
print(arr[-1])
print(arr[10])
print(arr[6])
print(arr[9])
# print(arr[18])  

10
95
60
40
55


In [21]:
print(arr[2:10])
print(arr[2:3])
print(arr[10:19])
print(arr[-10:-5])
print(arr[-10:])

[20 25 30 35 40 45 50 55]
[20]
[60 65 70 75 80 85 90 95]
[50 55 60 65 70]
[50 55 60 65 70 75 80 85 90 95]


In [22]:
## filtering condtions

arr = np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [29]:
print(arr<100) ## ><=
print(arr>100)
print(arr<=100)
print(arr>=100)

[ True  True False  True False  True  True False]
[False False  True False  True False False  True]
[ True  True False  True False  True  True False]
[False False  True False  True False False  True]


In [25]:
arr2 = np.array([True,True,False,False])
arr2

array([ True,  True, False, False])

In [ ]:
## Where is function which gives the index of the true values in the array. 
np.where(arr2) ## True = 1 , False = 0

(array([0, 1]),)

In [31]:
## Where function outputs index location of values meeting the condition.
np.where(arr<100)

(array([0, 1, 3, 5, 6]),)

In [32]:
import numpy as np


In [33]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [34]:
arr_2d[:,1]

array([ 2, 15, 96])

In [37]:
arr_2d[:,0]

array([ 1, 12, 64])

In [35]:
l1=[1,2,3,4,5]

In [36]:
l1[:3]

[1, 2, 3]

In [40]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [ ]:
arr_2d[:2,:2] 

array([[ 1,  2],
       [12, 15]])

In [42]:
arr_2d[:2,:3]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [46]:
arr_2d[:1,:3]

array([[1, 2, 3]])

In [44]:
arr_2d[:3,:3]

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [ ]:
arr3=np.arange(27).reshape(3,3,3) # Reshape(rows,columns,no.of elements)
arr3
 ## if we decide to parameter the row * columns
## valueerror is occur then check the reshape parameters.


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [ ]:
arr_2d[1:,:2] # Starting from 1 row and 2 columns

array([[12, 15],
       [64, 96]])

In [51]:
arr4 = np.arange(15).reshape(3,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
arr4 = np.arange(15).reshape(5,3)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [57]:
arr5 = np.arange(100).reshape(10,10)
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
arr_2d[1]

array([12, 15, 18])

In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy() # Copy the arr data to x variable.
x

array([1, 2, 3, 4, 5])

In [63]:
arr = np.array([1,2,3,4,5])
x = arr.view() # View the arr data to x variable.
x

array([1, 2, 3, 4, 5])

In [65]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [71]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3) # Split the array into 3 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [70]:
arr = np.array([3,2,0,1])
print(np.sort(arr)) # Sort the array in ascending order


[0 1 2 3]


In [72]:
arr = np.array(["This","is","a","test","array"])
print(np.sort(arr))

['This' 'a' 'array' 'is' 'test']


In [76]:
arr = np.array(["my","taleeb.","Is","name"])
print(np.sort(arr))

['Is' 'my' 'name' 'taleeb.']


In [73]:
arr = np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


In [77]:
arr_2d[1]

array([12, 15, 18])

In [78]:
arr = np.array([3,2,0,1])

for x in arr:
  print(x)

3
2
0
1


In [79]:
arr1=np.ones((10,10))
print(arr1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [83]:
for i in range(len(arr1)):
  arr1[i] = i #+ 1

arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [86]:
arr1=np.ones((10,10))
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
arr_2d = np.zeros(arr1.shape)
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
arr_2d.shape

(10, 10)

In [91]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [92]:
arr_2d[:,0]<4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])